name=SpikeSerial
version=0.1
author= Simon D. Levy<simon.d.levy@gmail.com>
maintainer=Simon D. Levy<simon.d.levy@gmail.com>
sentence=TeNNLab FPGA spike serializer
paragraph=TeNNLab FPGA spike serializer
category=Other
url=https://bitbucket.org/neuromorphic-utk/embedded-framework-simon/src/master/fpga/
architectures=*
includes=fpga_client.h
