# Copyright (c) 2026 Simon D. Levy
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

all: test

ROOT = ../..

SRC = $(ROOT)/src

NET = $(ROOT)/networks/xor.txt

test: main.cpp xor.hpp $(SRC)/*.hpp
	g++ -Wall -I$(SRC) -o test main.cpp

xor.hpp: $(NET)
	$(ROOT)/utils/mkhdr.py $(NET) -o ./xor.hpp

run: test
	./test

edit:
	vim main.cpp

clean:
	rm -rf test xor.hpp
