# Copyright (c) 2026 Simon D. Levy
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

SRC = ../../src

all: test

test: main.cpp ../serial.cpp $(SRC)/*.h*
	g++ -Wall -I$(SRC) -o test main.cpp ../serial.cpp

run: test
	./test

edit:
	vim main.cpp

clean:
	rm -rf test simple *.o
